# Generated by Django 3.2.25 on 2024-07-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.modalidad'),
        ),
    ]
