# Generated by Django 3.2.25 on 2024-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_horario_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia_fin',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia_inicio',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='semana_fin',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='semana_inicio',
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
