# Generated by Django 3.2.25 on 2024-07-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240729_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
