# Generated by Django 5.0.7 on 2024-07-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_materia_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='electiva',
            field=models.BooleanField(default=False),
        ),
    ]
