# Generated by Django 5.0.7 on 2024-07-30 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_materia_electiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='modalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.modalidad'),
        ),
    ]
