# Generated by Django 5.0.7 on 2024-08-01 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_horario_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.modalidad'),
        ),
    ]
